lesson3 CreateModel, SetDefVal, SetNullConstraints
RuslanKLESK/test-guru pull request #2
Opened 2021-09-18 12:54 UTC by RuslanKLESK

Вторая часть задания для урока 3.
Созданы модели, установлены ограничения и параметры по умолчанию.

2021-09-18 18:44 UTC, BubuntuClu requested changes

2021-09-18 18:44 UTC, BubuntuClu commented on db/migrate/20210918114847_create_tests.rb
> +      t.references :category, null: false, foreign_key: true
править смерженные миграции нельзя. нужно убрать эту строку и создать отдельную миграцию на добавление этого поля в таблицу

2021-09-18 20:07 UTC, RuslanKLESK commented on db/migrate/20210918114847_create_tests.rb
> +      t.references :category, null: false, foreign_key: true
Примерно неделю назад я создал миграцию  "bin/rails g model test title:string level:integer"
И накатил её.
Чуть позже понял, что не полностью всё указал в миграции, потому:
- rollback миграции выполнил.

Сегодня удалил физически 4 файла (сам файл миграции недельной давноcти, app-model-test.rb,  test-tests.yml, fixtures-tests.yml)
И создал заново правильную модель test.  Миграция создана из консоли с помощью "bin/rails g model test title:string level:integer category:references"
Далее накатана через "bin/rails db:migrate"

Вручную не правил модели.
Вручную правил  только созданные через генератор миграций :значения по умолчанию и запрет пустых значений.

2021-09-19 18:29 UTC, BubuntuClu commented on db/migrate/20210918114847_create_tests.rb
> +      t.references :category, null: false, foreign_key: true
если ты ее удалил и создал заного то у тебя должно было поменяться имя файла. файл не поменялся, значит ты его не удалил.

не буду мучать, но скорее всего все можно сделать, то что выше написано. в след раз до победного буду мучать

2021-09-21 17:24 UTC, merged