Lesson4
RuslanKLESK/test-guru pull request #4
Opened 2022-05-16 22:09 UTC by RuslanKLESK

- Урок 4 с исправлениями(методы исправил, работают) и Урок 5 (был открыт авансом).
Всё проверил, работает.

- ER-диаграмма сохранена физически в проекте test-guru (в моделях - файл доступа к проекту на drawio и статическая страница  public).
и в вики - https://github.com/RuslanKLESK/test-guru/wiki/ER-diagram

2022-05-17 17:32 UTC, BubuntuClu requested changes

2022-05-17 17:32 UTC, BubuntuClu commented on app/models/test.rb
> +    Test.joins('JOIN categories ON tests.category_id = categories.id').where('categories.title = :title', title: category).order(title: :desc).pluck(:title) #it`s work!
отрефактори запрос с использованием ассоциации `category`

2022-05-17 17:32 UTC, BubuntuClu commented on app/models/test.rb
> +
>Между Тестом и автором (Пользователем), который его создал.

нужно добавить еще ассоциацию на авторство теста

2022-05-17 17:32 UTC, BubuntuClu commented on app/models/question.rb
> +  has_many :answer
ассоциация должна быть во множественном числе

2022-05-17 17:32 UTC, BubuntuClu commented on app/models/user.rb
> +    Test.where(level: level).joins('JOIN tests_users ON tests_users.test_id = tests.id').where(tests_users: {user_id: id})
отрефактори запрос с использованием ассоции `tests`

2022-05-17 17:32 UTC, BubuntuClu commented on app/models/user.rb
> +
>Между Тестом и автором (Пользователем), который его создал.

нужно добавить ассоциацию на созданные тесты пользователем

2022-05-17 17:32 UTC, BubuntuClu commented on db/migrate/20220515120245_create_tests_users_join_table.rb
> +      t.index [:user_id, :test_id], unique: true
уникальный индекс ограничивает функционал приложения. пользователь не сможет проходить тест несколько раз. ты уверен что хочешь сделать такое ограничение?

2022-05-17 17:32 UTC, BubuntuClu commented on db/migrate/20220515120245_create_tests_users_join_table.rb
> +      t.index [:test_id, :user_id], unique: true  # Для большей функциональности таблицы.
что за бОльшая функциональность?

2022-05-17 17:32 UTC, BubuntuClu commented on db/migrate/20220516173119_add_progress_to_tests_users.rb
> +    add_column :tests_users, :progress, :integer, default: 0
у тебя выше миграция на создание таблицы соединитильной. зачем отдельная миграция на добавление колонки в эту таблицу? за раз в одной миграции сделай все что нужно для таблицы.

и лучше использовать обычный `create_table`, чем `create_join_table`. ты ведь не знаешь понадобится ли тебе `id` столбец в соединительной таблице, так что лучше пусть он будет, чем потом мучаться с его добавлением

2022-05-17 17:32 UTC, BubuntuClu commented on db/seeds.rb
> +  {user_id: 1, test_id: 1},
нельзя хардкодить id. если несколько раз накатывать сид, то у тебя может не быть таких ID объектов и не будет ничего создано. используй объекты, что создавал выше

2022-05-19 07:12 UTC, BubuntuClu requested changes

2022-05-19 07:12 UTC, BubuntuClu commented on app/models/test.rb
> +  belongs_to :user # для связи между Тестом и автором (Пользователем), который его создал.
в чем разница между `user` и `users`. из названия не понятно, только в количествах объектов что вернется. нужно сделать так, чтобы ассоциация была говорящей и было без комментариев понятно что она возвращает. посмотри в сторону опции `class_name` чтобы задать кастомное имя ассоциации

2022-05-19 07:12 UTC, BubuntuClu commented on app/models/user.rb
> +  has_many :tests # для связи между Тестом и автором (Пользователем), который его создал.
у тебя две ассоциации с одним именем. это не будет работать. надо переделать

2022-05-19 07:12 UTC, BubuntuClu commented on app/models/user.rb
> +    Test.where(level: level).joins(:tests_users).where(tests_users: {user_id: id})  #better
можно еще подумать. тут сократить весь запрос можно до 4 слов

2022-05-19 09:32 UTC, RuslanKLESK commented on app/models/user.rb
> +    Test.where(level: level).joins(:tests_users).where(tests_users: {user_id: id})  #better
Test.where(level: level).joins(tests_users: {user_id: id})

2022-05-19 21:47 UTC, RuslanKLESK commented on app/models/test.rb
> +  belongs_to :user # для связи между Тестом и автором (Пользователем), который его создал.
class_name   крутая штука...   Надо было в скринкасте рассказать.

2022-05-21 18:04 UTC, BubuntuClu approved these changes

2022-05-21 18:04 UTC, BubuntuClu commented on app/models/user.rb
> +    tests.where(level: level).joins(:tests_users).where(tests_users: {user_id: id}) # в нсоле: u = User.last, u.all_tests_of_user_by_level(2)  = Получаю 3 теста, вместо одного...
`.joins(:tests_users).where(tests_users: {user_id: id})` это все лишнее. у тебя фильтрация происходит при вызове `user.tests`, так как ассоциация вызывается от конкретного пользователя

2022-05-21 18:04 UTC, BubuntuClu commented on app/models/test.rb
> +    # Test.joins('JOIN categories ON tests.category_id = categories.id').where('categories.title = :title', title: category).order(title: :desc).pluck(:title) #it`s work!
ненужный код удаляй, не нужно хлам весь сохранять, чтобы он мешался

2022-05-21 18:04 UTC, BubuntuClu commented on app/models/user.rb
> +    # Test.where(level: level).joins('JOIN tests_users ON tests_users.test_id = tests.id').where(tests_users: {user_id: id})
и тут все лишнее надо удалить

2022-05-22 10:20 UTC, merged