lesson_6 feat(model): scope-methods, validates (v.1)
RuslanKLESK/test-guru pull request #5
Opened 2022-05-28 18:07 UTC by RuslanKLESK

Please check my torment

2022-05-28 19:34 UTC, BubuntuClu requested changes

2022-05-28 19:34 UTC, BubuntuClu commented on app/models/test.rb
> +  scope :all_tests_of_category, -> (category) { Test.joins(:category).where(categories: {title: category}).order(title: :desc).pluck(:title) }
сортировку и выборку не надо помещать в скоуп.
скоуп должен возвращать объект ActiveRecord::Relation, pluck возвращает массив.
так же скоуп это универсальный метод, который может использован в разных частях приложения, там может потребоваться другая сортировка и выборка.
метод надо оставить, заменить часть выражения на скоуп и уже к скоупу применить сортировку и выборку

2022-05-28 19:34 UTC, BubuntuClu commented on app/models/test.rb
> +  validate :validate_max_level, on: :create
есть стандартная опция для подобной валиадции, используй ее вместо кастомной

2022-05-28 19:34 UTC, BubuntuClu commented on app/models/test.rb
> +  validates :title, :level, uniqueness: true
уникальной должна быть пара значений title+level, а не каждый в отдельности

2022-05-28 19:34 UTC, BubuntuClu commented on app/models/user.rb
> +  scope :all_tests_of_user_by_level, -> (level) { tests.where(level: level) }
это не будет работать так же как и метод. метод не поулчится в скоуп преобразовать

2022-05-28 19:34 UTC, BubuntuClu commented on app/models/answer.rb
> +    errors.add('You cannot add more than 4 answers') if question.answers.length > 4
первым аргументом в `add` идет имя ключа, в который добавится текст ошибки, вторым аргументом сам текст ошибки

2022-05-28 19:34 UTC, BubuntuClu commented on app/models/category.rb
> +  validates :title, presence: true, uniqueness: true
ограничения надо дублировать на всех уровнях приложения. можно через СУБД насоздавать данных, которые для приложения не будут валидны. в БД добавить уникальный индекс надо

2022-05-28 19:34 UTC, BubuntuClu commented on app/models/test.rb
> +  validates :title, :level, uniqueness: true
ограничения надо дублировать на всех уровнях приложения. можно через СУБД насоздавать данных, которые для приложения не будут валидны. в БД добавить уникальный составной индекс надо

2022-06-05 14:09 UTC, RuslanKLESK commented on app/models/category.rb
> +  validates :title, presence: true, uniqueness: true
DRY)

2022-06-05 18:17 UTC, BubuntuClu commented on app/models/test.rb
> +    tests_of_category.where(categories: {title: category}).order(title: :desc).pluck(:title)
`where` тоже в скоуп помести

2022-06-05 18:17 UTC, BubuntuClu commented on app/models/user.rb
> +  has_many :authors, class_name: 'Test', foreign_key: "test_id"
`User.authors` - а вызов такой вернет тесты, по названию не подходит. `created_tests/authored_tests` лучше использовать

2022-06-06 16:26 UTC, merged